<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Profesor" Id="{b7884ec5-07e8-4a6e-9269-8fa6a6554ecf}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Profesor EXTENDS Persona IMPLEMENTS ITF_Profesor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	_Nombre: STRING;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="DarClases" Id="{6b209387-2537-402c-81fd-921a69adf89b}">
      <Declaration><![CDATA[METHOD DarClases
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Fichar" Id="{f9336cb5-f090-43e7-b6db-0621fc018b38}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD Fichar
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Nombre" Id="{17598f38-9bdf-45fe-9441-8725ae07811a}">
      <Declaration><![CDATA[PROPERTY Nombre : String]]></Declaration>
      <Get Name="Get" Id="{87b041bc-6822-43ec-93ad-c40b1360a8ff}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{e220a405-94dc-4330-b6e9-48301bcf83cf}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="Salida" Id="{faf22ff7-7886-4e56-8833-347250fbf2c2}">
      <Declaration><![CDATA[{warning 'Agregar implementación de propiedad'}
PROPERTY Salida : INT
]]></Declaration>
      <Get Name="Get" Id="{f6a5a615-9366-45bd-ba8d-e9f12554731e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{bca320ab-790c-4e80-90bd-4a763e48037e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="UMLStereoTypeContainerObject">
            <v n="IsType" t="UMLType">BaseArea</v>
            <v n="Stereotype">""</v>
            <d n="Stereotypes" t="Hashtable" />
          </o>
        </Data>
        <TypeList>
          <Type n="Hashtable">System.Collections.Hashtable</Type>
          <Type n="String">System.String</Type>
          <Type n="UMLStereoTypeContainerObject">{30250973-b110-4e31-b562-c102e042dca4}</Type>
          <Type n="UMLType">{0197b136-405a-42ee-bb27-fd08b621d0cf}</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
  </POU>
</TcPlcObject>