<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Coche1" Id="{cc8ecd1f-0cd7-4903-9c1f-7a7af02f9dfa}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Coche1 EXTENDS Vehiculo
VAR_INPUT
	velocidadMaxima : REAL;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Mover" Id="{3881cff0-6e5a-4f89-b566-859812957a0b}">
      <Declaration><![CDATA[
METHOD Mover : REAL
VAR_INPUT
	Velocidad_Deseada : REAL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[Mover := Velocidad_Deseada * velocidadMaxima;]]></ST>
      </Implementation>
    </Method>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="UMLStereoTypeContainerObject">
            <v n="IsType" t="UMLType">BaseArea</v>
            <v n="Stereotype">""</v>
            <d n="Stereotypes" t="Hashtable" />
          </o>
        </Data>
        <TypeList>
          <Type n="Hashtable">System.Collections.Hashtable</Type>
          <Type n="String">System.String</Type>
          <Type n="UMLStereoTypeContainerObject">{30250973-b110-4e31-b562-c102e042dca4}</Type>
          <Type n="UMLType">{0197b136-405a-42ee-bb27-fd08b621d0cf}</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
  </POU>
</TcPlcObject>