<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Moto1" Id="{3ad43376-49ab-444b-a93a-f983711d4a1e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Moto1 EXTENDS Vehiculo
VAR_INPUT
	Aceleracion : REAL;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Mover" Id="{f6b9738a-e6e2-49b6-8dfb-d1e036957184}">
      <Declaration><![CDATA[
METHOD Mover : REAL
VAR_INPUT
	Velocidad_Deseada : REAL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[Mover := Velocidad_Deseada * Aceleracion ;]]></ST>
      </Implementation>
    </Method>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="UMLStereoTypeContainerObject">
            <v n="IsType" t="UMLType">BaseArea</v>
            <v n="Stereotype">""</v>
            <d n="Stereotypes" t="Hashtable" />
          </o>
        </Data>
        <TypeList>
          <Type n="Hashtable">System.Collections.Hashtable</Type>
          <Type n="String">System.String</Type>
          <Type n="UMLStereoTypeContainerObject">{30250973-b110-4e31-b562-c102e042dca4}</Type>
          <Type n="UMLType">{0197b136-405a-42ee-bb27-fd08b621d0cf}</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
  </POU>
</TcPlcObject>