<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Vehiculo" Id="{d9f89bc7-2a9b-4dca-a00a-6ec7dcda740f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Vehiculo IMPLEMENTS I_Mover

]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Mover" Id="{e36f3dcf-1ae2-4c88-a575-1852fbfc4d20}">
      <Declaration><![CDATA[
METHOD Mover : REAL
VAR_INPUT
	Velocidad_Deseada : REAL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[Mover := Velocidad_Deseada;]]></ST>
      </Implementation>
    </Method>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="UMLStereoTypeContainerObject">
            <v n="IsType" t="UMLType">BaseArea</v>
            <v n="Stereotype">""</v>
            <d n="Stereotypes" t="Hashtable" />
          </o>
        </Data>
        <TypeList>
          <Type n="Hashtable">System.Collections.Hashtable</Type>
          <Type n="String">System.String</Type>
          <Type n="UMLStereoTypeContainerObject">{30250973-b110-4e31-b562-c102e042dca4}</Type>
          <Type n="UMLType">{0197b136-405a-42ee-bb27-fd08b621d0cf}</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
  </POU>
</TcPlcObject>