<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="AbstractLoadCell" Id="{eac44cb8-b49a-4f2c-ace6-1b4d9fed91c1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT AbstractLoadCell
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="GetActualValue" Id="{3da4c0e9-16f4-4522-b7df-ec2fd5b3707a}">
      <Declaration><![CDATA[METHOD PUBLIC ABSTRACT GetActualValue : LREAL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>