<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_AirConComfortCommand" Id="{00077904-e3e1-4935-8970-a95d5a9de915}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC FB_AirConComfortCommand IMPLEMENTS I_Command
VAR
	refAirConditioning : REFERENCE TO FB_AirConditioning;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Execute" Id="{a57f8a00-c1a2-4722-a9da-0cccf07d9ad8}">
      <Declaration><![CDATA[METHOD Execute
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(THIS^.refAirConditioning)) THEN
	THIS^.refAirConditioning.Activate();
	THIS^.refAirConditioning.SetTemperature(20.0);
END_IF
]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{36e1f83d-9f25-43a1-be24-18c79e1ea78f}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	refAirConditioning : REFERENCE TO FB_AirConditioning;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(refAirConditioning)) THEN
	THIS^.refAirConditioning REF= refAirConditioning;
ELSE
	THIS^.refAirConditioning REF= 0;
END_IF
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>