<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="_16_Interface_vs_Herencia" Id="{f91f7753-0f8e-42cd-b8fd-96db2bd303ab}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM _16_Interface_vs_Herencia
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[P_Light_Test_ST();
P_Light_Test_CFC();

P_DelayedLight_Test_ST();
P_DelayedLight_Test_CFC();

P_DimmingLight_Test_ST();
P_DimmingLight_Test_CFC();

P_MyLight_Test_ST();
P_MyLight_Test_CFC();

P_RoomController_Test_ST();
P_RoomController_Test_CFC();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>