<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="_27_SOLID_ISP" Id="{f7c89670-3872-4535-98ac-59febddcaf08}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM _27_SOLID_ISP
VAR
	Patito_feo : Pato;
	Aguila_imperial : Aguila;
	Avestruz_de_cuello_azul : Avestruz;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Patito_feo.Nadar();
Patito_feo.Volar();

Aguila_imperial.Volar();

Avestruz_de_cuello_azul.Correr();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>