<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_MusicPlayCommand" Id="{089a3154-c8b5-4cc0-8e8c-b401bf03e12c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC FB_MusicPlayCommand IMPLEMENTS I_Command
VAR
	refCDPlayer : REFERENCE TO FB_CDPlayer;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Execute" Id="{4da12abf-96a4-4d0e-a7f4-2340d374c6bd}">
      <Declaration><![CDATA[METHOD Execute
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(THIS^.refCDPlayer)) THEN
	THIS^.refCDPlayer.SetVolume(40);
	THIS^.refCDPlayer.SetTrack(1);
	THIS^.refCDPlayer.Start();
END_IF
]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{1a6c2116-6de7-47af-b867-29c513a7a2d2}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	refCDPlayer : REFERENCE TO FB_CDPlayer;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(refCDPlayer)) THEN
	THIS^.refCDPlayer REF= refCDPlayer;
ELSE
	THIS^.refCDPlayer REF= 0;
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="Undo" Id="{0b52a410-f7bb-4718-b299-09bc3da2601e}">
      <Declaration><![CDATA[METHOD Undo
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(THIS^.refCDPlayer)) THEN
	THIS^.refCDPlayer.Stop();
END_IF
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>