<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_MusicStopCommand" Id="{a1d54cf0-4329-407d-be2e-58569ba4a8a7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC FB_MusicStopCommand IMPLEMENTS I_Command
VAR
	refCDPlayer : REFERENCE TO FB_CDPlayer;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Execute" Id="{1a31b470-82ab-4d3a-a1be-6d43a3255320}">
      <Declaration><![CDATA[METHOD Execute
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(THIS^.refCDPlayer)) THEN
	THIS^.refCDPlayer.Stop();
END_IF
]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{7acd4688-d898-4766-9e34-1d82a4972629}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	refCDPlayer : REFERENCE TO FB_CDPlayer;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(refCDPlayer)) THEN
	THIS^.refCDPlayer REF= refCDPlayer;
ELSE
	THIS^.refCDPlayer REF= 0;
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="Undo" Id="{bdee52f1-1b95-4630-81e4-a5e10d4b74cb}">
      <Declaration><![CDATA[METHOD Undo
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(THIS^.refCDPlayer)) THEN
	THIS^.refCDPlayer.SetVolume(40);
	THIS^.refCDPlayer.SetTrack(1);
	THIS^.refCDPlayer.Start();
END_IF
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>