<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_SocketOffCommand" Id="{59031cb0-1992-4ca7-b8f1-c9aabbb47879}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC FB_SocketOffCommand IMPLEMENTS I_Command
VAR
	refSocket : REFERENCE TO FB_Socket;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Execute" Id="{ebace1ea-7d38-4762-951b-29c07047bf80}">
      <Declaration><![CDATA[METHOD Execute]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(THIS^.refSocket)) THEN
	THIS^.refSocket.Off();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{a7a2b0f7-3cdf-417a-bc3c-9eb3c2a4ac1e}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	refNewSocket : REFERENCE TO FB_Socket;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(refNewSocket)) THEN
	THIS^.refSocket REF= refNewSocket;
ELSE
	THIS^.refSocket REF= 0;
END_IF
]]></ST>
      </Implementation>
    </Method>
    <Method Name="Undo" Id="{2152f5d3-4a1c-4747-b76d-b665cbd4937e}">
      <Declaration><![CDATA[METHOD Undo
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(THIS^.refSocket)) THEN
	THIS^.refSocket.On();
END_IF]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>