<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Square" Id="{23435c1e-9e24-49e2-a19f-fbbf3c4adf36}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FB_Square IMPLEMENTS I_Shape
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_Draw" Id="{c62d25ec-9308-461b-98be-565313cc7da3}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD M_Draw : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_HINT, 'Square', '');
M_Draw := TRUE;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>