<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Star" Id="{4d616224-ec60-425f-8046-aa3392519073}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FB_Star IMPLEMENTS I_Shape
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_Draw" Id="{db068f4e-e9bb-4385-ae03-c5b17c4dfd7f}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD M_Draw : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_HINT, 'Draw Star', '');
M_Draw := TRUE;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>