<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="fbreturn5" Id="{9c594cfb-17d1-49ed-93c8-d821f6533f37}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fbreturn5
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>