<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Humano" Id="{d4a32384-1ff2-4dfd-8276-2238a328a67c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Humano IMPLEMENTS I_Humano
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Correr" Id="{ab751311-0c3f-42a9-aced-90d53b2c17b9}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD Correr
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Nombre" Id="{e40449f4-a3e0-409c-92f6-4841bff99f06}">
      <Declaration><![CDATA[{warning 'Agregar implementación de propiedad'}
PROPERTY Nombre : STRING
]]></Declaration>
      <Get Name="Get" Id="{0beb7bab-28f8-4ee2-a443-6e46b3829b63}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{a701ccd5-5fdb-423c-9b59-1206c62c592b}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="UMLStereoTypeContainerObject">
            <v n="IsType" t="UMLType">BaseArea</v>
            <v n="Stereotype">""</v>
            <d n="Stereotypes" t="Hashtable" />
          </o>
        </Data>
        <TypeList>
          <Type n="Hashtable">System.Collections.Hashtable</Type>
          <Type n="String">System.String</Type>
          <Type n="UMLStereoTypeContainerObject">{30250973-b110-4e31-b562-c102e042dca4}</Type>
          <Type n="UMLType">{0197b136-405a-42ee-bb27-fd08b621d0cf}</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
  </POU>
</TcPlcObject>