<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.3">
  <POU Name="FB_Lamp" Id="{c9363aa1-33e3-41da-adea-7faeb59d6855}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC FB_Lamp
VAR_OUTPUT
	byLevel			: BYTE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Level" Id="{14dcd475-0945-4468-8762-cbfbbeb1403d}">
      <Declaration><![CDATA[PROPERTY PUBLIC Level : BYTE]]></Declaration>
      <Get Name="Get" Id="{48f1de5c-993e-42ec-a2e6-7dc3b36570be}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Level := byLevel;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="SetLevel" Id="{97c2b33b-5c80-46f7-8f00-32f4f1bdd6a5}">
      <Declaration><![CDATA[METHOD PUBLIC SetLevel : BOOL
VAR_INPUT
	byNewLevel			:	BYTE;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[byLevel := byNewLevel;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>