<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{791988f4-6222-4a77-9850-9cca8d50763e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Video de Youtube 02:
_02_Clase_y_Objetos();

// Video de Youtube 03:
_03_Clase_y_Objetos();

// Video de Youtube 04:
_04_Clases_y_Objetos();

// Video de Youtube 05;
_05_Metodo();

// Video de Youtube 06;
_06_Propiedad();

// Video de Youtube 07;
_07_Herencia();

// Video de Youtube 08;
_08_Herencia_Estructura_y_Interface();

// Video de Youtube 09;
_09_THIS_SUPER();

// Video de Youtube 10;
_10_Interface();

// Video de Youtube 11;
_11_Puntero_y_Referencia();

// Video de Youtube 12;
_12_Concepto_Keyword_Abstract();

// Video de Youtube 13;
_13_1_Main_Abstract();
_13_2_Main_Interfaz();
_13_3_Main_Combinacion();

// Video de Youtube 14;
_14_Interface_Fluida();

// Video de Youtube 15:
_15_Interface_vs_Herencia();

// Video de Youtube 16:
_16_Interface_vs_Herencia();

// Video de Youtube 17:
_17_Otros_Operadores();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>