<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{791988f4-6222-4a77-9850-9cca8d50763e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Video de Youtube 02:
_02_Clase_y_Objetos();

// Video de Youtube 03:
_03_Clase_y_Objetos();

// Video de Youtube 04:
_04_Clases_y_Objetos();

// Video de Youtube 05;
_05_Metodo();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>